version: "3"

services:
  database:
    image: postgres:17.4-alpine3.21
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - bps_backend
  # app:
  #   build:
  #     context: .
  #   ports:
  #     - ${PORT}:${PORT}
  #   environment:
  #     PORT: ${PORT}
  #   networks:
  #     - bps_backend
  #   depends_on:
  #     - database

networks:
  bps_backend:
    driver: bridge
